"""add job skillkind

Revision ID: 002f4749d77b
Revises: 192cb15b075d
Create Date: 2019-03-17 17:34:12.862708

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002f4749d77b'
down_revision = '192cb15b075d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('skill_kind',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('skill', sa.Column('icon', sa.String(length=100), nullable=True))
    op.add_column('skill', sa.Column('job_id', sa.Integer(), nullable=True))
    op.add_column('skill', sa.Column('ref', sa.String(length=100), nullable=True))
    op.add_column('skill', sa.Column('skill_kind_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'skill', 'skill_kind', ['skill_kind_id'], ['id'])
    op.create_foreign_key(None, 'skill', 'job', ['job_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_constraint(None, 'skill', type_='foreignkey')
    op.drop_column('skill', 'skill_kind_id')
    op.drop_column('skill', 'ref')
    op.drop_column('skill', 'job_id')
    op.drop_column('skill', 'icon')
    op.drop_table('skill_kind')
    op.drop_table('job')
    # ### end Alembic commands ###
