"""update skill icon length

Revision ID: 16fb06b379a2
Revises: c19035adada0
Create Date: 2019-03-17 17:50:42.121437

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '16fb06b379a2'
down_revision = 'c19035adada0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
