"""empty message

Revision ID: 192cb15b075d
Revises: 16eb8ab81f4a
Create Date: 2019-03-17 17:05:22.983406

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '192cb15b075d'
down_revision = '16eb8ab81f4a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('skill', 'consume')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('skill', sa.Column('consume', mysql.VARCHAR(length=100), nullable=True))
    # ### end Alembic commands ###
