"""update skill icon length

Revision ID: 69edb1718cad
Revises: 002f4749d77b
Create Date: 2019-03-17 17:47:43.424062

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69edb1718cad'
down_revision = '002f4749d77b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
