"""update skill icon length

Revision ID: 89e86b960983
Revises: 69edb1718cad
Create Date: 2019-03-17 17:48:26.793949

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e86b960983'
down_revision = '69edb1718cad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
