"""update skill icon length

Revision ID: c19035adada0
Revises: 89e86b960983
Create Date: 2019-03-17 17:48:56.629065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c19035adada0'
down_revision = '89e86b960983'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
